```{r fig2-load}
library (pkgstatsAnalyses)
library (dplyr, quietly = TRUE, warn.conflicts = FALSE)
library (tidyr)
library (ggplot2)
library (patchwork)
```

```{r fig2-prepro}
here <- file.path (here::here (), "2026", "useR2026")
v_data_dir <- file.path (here, "data")

datafile <- file.path (here, "data-raw", "pkgstats-results.Rds")
f_fig2_top10 <- file.path (v_data_dir, "fig02-top10.Rds")
f_fig2_tr <- file.path (v_data_dir, "fig02-tr.Rds")
fig2_calc_top10_data <- !file.exists (f_fig2_top10)
fig2_calc_tr_data <- !file.exists (f_fig2_tr)

fig07_png <- file.path (here, "img", "fig07.png")
fig2_calc_top10_data <- fig2_calc_top10_data & !file.exists (fig07_png)
fig2_calc_tr_data <- fig2_calc_tr_data & !file.exists (fig07_png)
```


```{r fig2_tr_data, eval = fig2_calc_tr_data}
x <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE)
x$translations [x$translations == "NA"] <- NA_character_

tr <- lapply (split (x, f = as.factor (x$year)), function (i) {
    tr <- strsplit (i$translations, ",") |>
        unlist () |>
        basename ()
    tr <- gsub ("\\s*|^R\\-", "", grepv ("^R\\-", tr))
    tab <- sort (table (tr), decreasing = TRUE)
    data.frame (
        translation = names (tab),
        n = as.integer (tab)
    )
})
tr <- tr [which (vapply (tr, nrow, integer (1)) > 0)]
for (i in seq_along (tr)) {
    tr [[i]]$year <- names (tr) [i]
}
tr <- do.call (rbind, tr)
rownames (tr) <- NULL
tr$year <- lubridate::year (paste0 (tr$year, "-01-01"))

# total numbers of packages for each year:
n <- x |>
    group_by (year) |>
    summarise (n = n ())
tr$ntot <- n$n [match (tr$year, n$year)]

tr_summary <- tr |>
    group_by (translation) |>
    summarise (n = sum (n)) |>
    arrange (desc (n)) |>
    filter (translation != "en@quot")
top10 <- tr_summary$translation [1:10]
tr_top10 <- tr [which (tr$translation %in% top10), ]

tr_all <- tr |>
    group_by (year) |>
    summarise (n = sum (n),
               ntot = head (ntot, 1))
tr_all$translation <- "ALL"

tr_top10 <- bind_rows (tr_top10, tr_all)

saveRDS (tr_top10, f_fig2_tr)
```




```{r fig2-make, echo = FALSE, message = FALSE, eval = !file.exists (fig07_png)}

tr <- readRDS (f_fig2_tr) |>
    filter (!translation %in% c ("ALL", "en@quot"))
tr$proportion <- tr$n / tr$ntot

levels <- tr |>
    group_by (translation) |>
    summarise (n = n ()) |>
    arrange (desc (n))
tr$translation <- factor (tr$translation, levels = levels$translation)

tr |>
    ggplot (aes (x = year, y = proportion, color = translation)) +
    geom_line (lwd = 1.2) +
    xlab ("Year") +
    ylab ("Count") +
    guides (color = guide_legend (ncol = 2)) +
    theme (
        text = element_text (size = 20),
        legend.title = element_blank (),
        legend.position = c (0.32, 0.78),
        legend.background = element_rect(fill='transparent', colour=NA),
        panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', color=NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill='transparent', colour=NA)
    ) -> p7
ggsave (fig07_png, p7, bg = "transparent", width = 10, height = 7)
```

