```{r fig3-load}
library (pkgstatsAnalyses)
library (dplyr, quietly = TRUE, warn.conflicts = FALSE)
library (tidyr)
library (ggplot2)
library (patchwork)
```

```{r fig3-n-files-data-load}
here <- file.path (here::here (), "2026", "useR2026")
v_data_dir <- file.path (here, "data")
logmean <- function (x, ...) {
    10 ^ mean (log10 (x [which (x > 0)]), na.rm = TRUE)
}

datafile <- file.path (here, "data-raw", "pkgstats-results.Rds")

fig08_png <- file.path (here, "img", "fig08.png")
f_fig3_pkg_level <- file.path (v_data_dir, "fig03-pkg-n-files.Rds")
do_fig3_pkg_n_files <- !file.exists (f_fig3_pkg_level) & !file.exists (fig08_png)
```

```{r fig3-n-files-data, eval = !n_files_exists & !file.exists (fig03_png)}
# takes a few tens of seconds
x <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE)
nfiles_one_year <- function (x, year = 2015) {
    # message (year)
    x1 <- x |>
        filter (year <= !!year) |>
        group_by (package) |>
        slice_max (date) |>
        summarise (R = logmean (files_R),
                   src = logmean (files_src),
                   inst = logmean (files_inst),
                   vignettes = logmean (files_vignettes),
                   tests = logmean (files_tests),
                   data = logmean (num_data_files))
    n_mean <- colMeans (x1 [, -1], na.rm = TRUE)

    c (year = year, n_mean)
}
dat <- vapply (sort (unique (x$year)), function (i)
               nfiles_one_year (x, i),
               numeric (7))
dat <- data.frame (t (dat))
dat$year <- lubridate::year (paste0 (dat$year, "-01-01"))

xy <- x |>
    group_by (year) |>
    summarise (R = logmean (files_R),
               src = logmean (files_src),
               inst = logmean (files_inst),
               vignettes = logmean (files_vignettes),
               tests = logmean (files_tests),
               data = logmean (num_data_files))

dat$what <- "cran_by_year"
xy$what <- "annual"

dat <- rbind (dat, xy)
dat$inst [!is.finite (dat$inst)] <- NA
dat$vignettes [!is.finite (dat$vignettes)] <- NA
dat$tests [!is.finite (dat$tests)] <- NA
dat$data [!is.finite (dat$data)] <- NA

saveRDS (dat, n_files_file)
```


```{r fig3-pkg-level-n-files, eval = do_fig3_pkg_n_files}
x_per_pkg <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE) |>
    group_by (package) |>
    mutate (seq = seq_len (n ())) |>
    ungroup () |>
    group_by (seq) |>
    summarise (
        R = mean (files_R, na.rm = TRUE),
        src = mean (files_src, na.rm = TRUE),
        inst = mean (files_inst, na.rm = TRUE),
        vignettes = mean (files_vignettes, na.rm = TRUE),
        tests = mean (files_tests, na.rm = TRUE),
        data = mean (num_data_files, na.rm = TRUE)
    ) |>
    filter (seq > 1) |>
    pivot_longer (cols = c (R, src, inst, vignettes, tests, data)) |>
    rename (dir = name)

saveRDS (x_per_pkg, f_fig3_pkg_level)
```


```{r fig3a, eval = !file.exists (fig03_png)}
dat <- readRDS (n_files_file) |>
    mutate (inst = inst * max (src, na.rm = TRUE) / max (inst, na.rm = TRUE)) |>
    filter (what == "cran_by_year") |>
    pivot_longer (cols = c (R, src, inst, vignettes, tests, data)) |>
    rename (n_files = value, dir = name)
levels <- dat |>
    group_by (dir) |>
    summarise (n_files = mean (n_files, na.rm = TRUE)) |>
    arrange (desc (n_files))
dat$dir <- factor (dat$dir, levels = levels$dir)

ggplot (dat, aes (x = year, y = n_files, color = dir)) +
    geom_line (lwd = 0.4, lty = 2, lwd = 1.5) +
    geom_smooth (method = "loess", formula = "y ~ x", se = FALSE, lwd = 1.0) +
    xlab ("Year") +
    ylab ("Num. files") +
    ylim (c (0, max (dat$n_files))) +
    theme (
        text = element_text (size = 20),
        legend.position = "none",
        panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', color=NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill='transparent', colour=NA)
    ) -> p8a

readRDS (f_fig3_pkg_level) |>
    mutate (dir = factor (dir, levels = levels$dir)) |>
    filter (seq <= 20) |>
    ggplot (aes (x = seq, y = value, colour = dir)) +
    geom_line (lwd = 0.4, lty = 2, lwd = 1.5) +
    geom_smooth (method = "loess", formula = "y ~ x", se = FALSE, span = 0.7, lwd = 1.0) +
    xlab ("Release Sequence") +
    ylab ("") +
    guides (color = guide_legend (ncol = 2)) +
    theme (
        text = element_text (size = 20),
        legend.title = element_blank (),
        legend.position = c (0.32, 0.85),
        legend.background = element_rect(fill = 'transparent', colour = NA),
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p8b

p8 <- p8a + p8b +
    plot_annotation (theme = theme (plot.background = element_rect (fill = "transparent", color = NA)))
ggsave (fig08_png, p8, bg = "transparent", width = 10, height = 7)
```

