```{r fig3-load}
library (pkgstatsAnalyses)
library (dplyr, quietly = TRUE, warn.conflicts = FALSE)
library (tidyr)
library (ggplot2)
library (patchwork)
```

```{r fig3-n-files-data-load}
here <- file.path (here::here (), "2026", "useR2026")
v_data_dir <- file.path (here, "data")
logmean <- function (x, ...) {
    10 ^ mean (log10 (x [which (x > 0)]), na.rm = TRUE)
}

datafile <- file.path (here, "data-raw", "pkgstats-results.Rds")
f_fns <- file.path (v_data_dir, "fig04-fns-per-year.Rds")

fig09_png <- file.path (here, "img", "fig09.png")
```

... Calculation code retained only in `pkgstats-analyses` repo.


```{r fig5-preload, eval = !file.exists (fig05_png)}
datafile <- file.path (here, "data-raw", "pkgstats-results.Rds")
x <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE) |>
        group_by (package) |>
        mutate (seq = seq_along (package))
x$loc_R [which (is.na (x$loc_R))] <- 0L
x$loc_src [which (is.na (x$loc_src))] <- 0L
x$loc_inst [which (is.na (x$loc_inst))] <- 0L
x$loc_total <- x$loc_R + x$loc_src + x$loc_inst
x$doclines_per_fn_exp_mn [which (!is.finite (x$doclines_per_fn_exp_mn))] <- NA
logmean <- function (x, ...) {
    10 ^ mean (log10 (x [which (x > 0)]), na.rm = TRUE)
}

x_rel <- x |>
    group_by (seq) |>
    summarise (
       loc = logmean (loc_total),
       loc_R = logmean (loc_R, na.rm = TRUE),
       loc_src = logmean (loc_src, na.rm = TRUE),
       loc_inst = logmean (loc_inst, na.rm = TRUE),
       n_fns_r_exported = logmean (n_fns_r_exported, na.rm = TRUE),
       n_fns_r_not_exported = logmean (n_fns_r_not_exported, na.rm = TRUE),
       n_fns_src = logmean (n_fns_src, na.rm = TRUE),
       n_fns_per_file_r = logmean (n_fns_per_file_r, na.rm = TRUE),
       n_fns_per_file_src = logmean (n_fns_per_file_src, na.rm = TRUE),
       npars_exported_mn = logmean (npars_exported_mn, na.rm = TRUE),
       npars_exported_md = logmean (npars_exported_md, na.rm = TRUE),
       loc_per_fn_r_mn = logmean (loc_per_fn_r_mn, na.rm = TRUE),
       loc_per_fn_r_md = logmean (loc_per_fn_r_md, na.rm = TRUE),
       loc_per_fn_r_exp_mn = logmean (loc_per_fn_r_exp_mn, na.rm = TRUE),
       loc_per_fn_r_exp_md = logmean (loc_per_fn_r_exp_md, na.rm = TRUE),
       loc_per_fn_r_not_exp_mn = logmean (loc_per_fn_r_not_exp_mn, na.rm = TRUE),
       loc_per_fn_r_not_exp_md = logmean (loc_per_fn_r_not_exp_md, na.rm = TRUE),
       loc_per_fn_src_mn = logmean (loc_per_fn_src_mn, na.rm = TRUE),
       loc_per_fn_src_md = logmean (loc_per_fn_src_md, na.rm = TRUE),
       doclines_per_fn_exp_mn = logmean (doclines_per_fn_exp_mn, na.rm = TRUE),
       doclines_per_fn_exp_md = logmean (doclines_per_fn_exp_md, na.rm = TRUE),
       doclines_per_fn_not_exp_mn = logmean (doclines_per_fn_not_exp_mn, na.rm = TRUE),
       doclines_per_fn_not_exp_md = logmean (doclines_per_fn_not_exp_md, na.rm = TRUE),
       docchars_per_par_exp_mn = logmean (docchars_per_par_exp_mn, na.rm = TRUE),
       docchars_per_par_exp_md = logmean (docchars_per_par_exp_md, na.rm = TRUE))
```

```{r}
readRDS (f_fns) |>
    filter (what == "annual") |>
    select (c (year, n_fns_r_exported, n_fns_r_not_exported, n_fns_src)) |>
    rename (r_exp = n_fns_r_exported,
            r_non = n_fns_r_not_exported,
            src = n_fns_src) |>
    pivot_longer (c (r_exp, r_non, src)) |>
    rename (type = name, number = value) |>
    mutate (type = recode_values (type,
        "r_exp" ~ "R (exp)",
        "r_non" ~ "R (non-exp)",
        "src" ~ "src")) |>
    mutate (type = factor (type, levels = c ("R (exp)", "R (non-exp)", "src"))) |>
    ggplot (aes (x = year, y = number, colour = type)) +
    geom_line (lwd = 1.5) +
    xlab ("Year") +
    ylab ("Numbers of functions") +
    theme (
        text = element_text (size = 20),
        legend.title = element_blank (),
        legend.position = c (0.32, 0.90),
        legend.background = element_rect(fill = 'transparent', colour = NA),
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p9a

x_rel |>
    select (c (seq, n_fns_r_exported, n_fns_r_not_exported, n_fns_src)) |>
    rename (r_exp = n_fns_r_exported,
            r_non = n_fns_r_not_exported,
            src = n_fns_src) |>
    filter (seq <= 100) |>
    pivot_longer (c (r_exp, r_non, src)) |>
    rename (type = name, number = value) |>
    mutate (type = recode_values (type,
        "r_exp" ~ "R (exp)",
        "r_non" ~ "R (non-exp)",
        "src" ~ "src")) |>
    mutate (type = factor (type, levels = c ("R (exp)", "R (non-exp)", "src"))) |>
    ggplot (aes (x = seq, y = number, colour = type)) +
        geom_line (lwd = 1.5) +
        xlab ("Release sequence") +
        ylab ("Numbers of functions") +
        guides (color = guide_legend (ncol = 2)) +
    theme (
        text = element_text (size = 20),
        legend.title = element_blank (),
        legend.position = "none",
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p9b

p9 <- p9a + p9b +
    plot_annotation (theme = theme (plot.background = element_rect (fill = "transparent", color = NA)))
ggsave (fig09_png, p9, bg = "transparent", width = 10, height = 7)
```

