```{r fig6-load}
library (pkgstatsAnalyses)
library (dplyr, quietly = TRUE, warn.conflicts = FALSE)
library (tidyr)
library (ggplot2)
library (patchwork)
```

```{r fig6-datafile}
here <- file.path (here::here (), "2026", "useR2026")
v_data_dir <- file.path (here, "data")
f_fig6_deps <- file.path (v_data_dir, "fig06-deps.Rds")
f_fns_seq <- file.path (v_data_dir, "fig07_deps_p1.Rds")
datafile <- file.path (here, "data-raw", "pkgstats-results.Rds")
fig13_png <- file.path (here, "img", "fig13.png")
```


```{r}
deps <- readRDS (f_fig6_deps) |> 
    filter (!is.na (year)) |>
    mutate (type = recode_values (type,
        "base" ~ "Base",
        "recommended" ~ "Recommended",
        "contributed" ~ "Contributed")) |>
    mutate (type = factor (type, levels = c ("Base", "Recommended", "Contributed")))
deps <- deps [deps$category == "unique", ]
deps_cran <- deps [deps$what == "cran_by_year", ]
deps <- deps [deps$what == "annual", ]

ggplot (deps, aes (x = year, y = proportion, colour = type)) +
    geom_line (lwd = 1.4) +
    geom_line (data = deps_cran, show.legend = FALSE, lty = 2) +
    xlab ("Year") +
    theme (
        text = element_text (size = 20),
        legend.title = element_blank (),
        legend.position = c (0.4, 0.50),
        legend.background = element_rect(fill = 'transparent', colour = NA),
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p13a

readRDS (f_fns_seq) |>
    filter (seq <= 50) |>
    mutate (name = recode_values (name,
        "n_base" ~ "Base",
        "n_recommended" ~ "Recommended",
        "n_contrib" ~ "Contributed")) |>
    mutate (name = factor (name, levels = c ("Base", "Recommended", "Contributed"))) |>
    ggplot (aes (x = seq, y = value, colour = name)) +
        geom_line (lty = 1, lwd = 1.5) +
        xlab ("Release sequence") +
        ylab ("") +
    theme (
        text = element_text (size = 20),
        legend.position = "none",
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p13b

p13 <- p13a + p13b +
    plot_annotation (theme = theme (plot.background = element_rect (fill = "transparent", color = NA)))
ggsave (fig13_png, p13, bg = "transparent", width = 12, height = 7)
```


