```{r fig6-load}
library (pkgstatsAnalyses)
library (dplyr, quietly = TRUE, warn.conflicts = FALSE)
library (tidyr)
library (ggplot2)
library (patchwork)
```

```{r fig6-datafile}
here <- file.path (here::here (), "2026", "useR2026")
v_data_dir <- file.path (here, "data")
datafile <- file.path (here, "data-raw", "pkgstats-results.Rds")
f_cpl_rel <- file.path (here, "data-raw", "couplings_releases.Rds")
fig19_png <- file.path (here, "img", "fig19.png")
logmean <- function (x, ...) {
    10 ^ mean (log10 (x [which (x > 0)]), na.rm = TRUE)
}
```


```{r}
deps_p3 <- readRDS (f_cpl_rel)
deps_p3$afferent_fns_per_pkg [which (is.na (deps_p3$afferent_fns_per_pkg))] <- 0L
deps_p3 <- deps_p3 |>
    group_by (seq) |>
    summarise (packages = logmean (afferent_npkgs),
        fns_per_pkg = logmean (afferent_fns_per_pkg)) |>
    filter (seq <= 50)
range_packages <- range (deps_p3$packages)
range_fns_per_pkg <- range (deps_p3$fns_per_pkg)
# colours from `ggplot_build(p1)$data`:
colours_p3 <- c ("Fns per pkg" = "#F8766D",
    "Packages" = "#00BFC4")
ggplot (deps_p3, aes (x = seq)) +
    geom_line (aes (y = packages, col = "Packages"), lwd = 1.5) +
    geom_line (aes (
        y = scales::rescale (fns_per_pkg, to = range_packages, from = range_fns_per_pkg),
        col = "Fns per pkg"), lwd = 1.5) +
    scale_y_continuous (
        name = "Packages",
        sec.axis = sec_axis (
            ~scales::rescale (., to = range_fns_per_pkg, from = range_packages),
            name = "Imported fns / pkg")) +
    xlab ("Release sequence") +
    scale_colour_manual (values = colours_p3) +
    theme (
        text = element_text (size = 20),
        legend.title = element_blank (),
        legend.position = c (0.2, 0.90),
        legend.background = element_rect(fill = 'transparent', colour = NA),
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p19
ggsave (fig19_png, p19, bg = "transparent", width = 10, height = 7)
```


