```{r fig6-load}
library (pkgstatsAnalyses)
library (dplyr, quietly = TRUE, warn.conflicts = FALSE)
library (tidyr)
library (ggplot2)
library (patchwork)
```

```{r fig6-datafile}
here <- file.path (here::here (), "2026", "useR2026")
v_data_dir <- file.path (here, "data")
graph_data_file <- file.path (v_data_dir, "fig08-graph-metrics.Rds")
graph_intern_data_file <-
    file.path (v_data_dir, "fig08-graph-metrics-intern.Rds")
datafile <- file.path (here, "data-raw", "pkgstats-results.Rds")
fig14_png <- file.path (here, "img", "fig14.png")
```

```{r}
readRDS (graph_intern_data_file) |>
    filter (what == "annual") |>
    select (year, starts_with ("n_")) |>
    rename (total = n_edges_rel, R = n_edges_rel_r, src = n_edges_rel_src) |>
    select (year, total, R, src, n_clusters) |>
    pivot_longer (c (total, R, src, n_clusters)) |>
    mutate (name = recode_values (name,
        "total" ~ "Total",
        "R" ~ "R",
        "src" ~ "src",
        "n_clusters" ~ "Clusters"
    )) |>
    mutate (name = factor (name, levels = c ("Total", "R", "src", "Clusters"))) |>
    ggplot (aes (x = year, y = value, colour = name)) +
    geom_line (lwd = 1.5) +
    xlab ("Year") +
    ylab ("Ratio edges/vertices") +
    theme (
        text = element_text (size = 20),
        legend.position = "none",
        legend.background = element_rect(fill = 'transparent', colour = NA),
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p14a
```

```{r}
xraw <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE)

logmean <- function (x, ...) {
    index <- which (x > 0 & !is.nan (x) & is.finite (x))
    10 ^ mean (log10 (x [index]), na.rm = TRUE)
}
x <- xraw |>
    group_by (package) |>
    mutate (nfns_total = n_fns_r + n_fns_src) |>
    mutate (seq = seq_along (package)) |>
    group_by (seq) |>
    summarise (
               #n_edges = mean (n_edges [which (!is.na (n_edges))]),
               #n_edges_r = mean (n_edges_r [which (!is.na (n_edges_r))]),
               #n_edges_src = mean (n_edges_src [which (!is.na (n_edges_src))]),
               #n_clusters = mean (n_clusters [which (!is.na (n_clusters))]),
               n_edges = logmean (n_edges / nfns_total, na.rm = TRUE),
               n_edges_r = logmean (n_edges_r / n_fns_r, na.rm = TRUE),
               n_edges_src = logmean (n_edges_src / n_fns_src, na.rm = TRUE),
               n_clusters = logmean (n_clusters, na.rm = TRUE),
               centr_dir_mn = logmean (centrality_dir_mn, na.rm = TRUE),
               centr_dir_md = logmean (centrality_dir_md, na.rm = TRUE),
               centr_dir_mn_no0 = logmean (centrality_dir_mn_no0, na.rm = TRUE),
               centr_dir_md_no0 = logmean (centrality_dir_md_no0, na.rm = TRUE),
               centr_undir_mn = logmean (centrality_undir_mn, na.rm = TRUE),
               centr_undir_md = logmean (centrality_undir_md, na.rm = TRUE),
               centr_undir_mn_no0 = logmean (centrality_undir_mn_no0, na.rm = TRUE),
                centr_undir_md_no0 = logmean (centrality_undir_md_no0, na.rm = TRUE),
                central_edges_dir = mean (num_terminal_edges_dir, na.rm = TRUE),
                term_edges = logmean (num_terminal_edges_undir, na.rm = TRUE),
                node_degree_mn = logmean (node_degree_mn, na.rm = TRUE),
                node_degree_md = logmean (node_degree_md, na.rm = TRUE),
                node_degree_max = logmean (node_degree_max, na.rm = TRUE))
```


```{r}
x |>
    select (seq, starts_with ("n_")) |>
    rename (total = n_edges, R = n_edges_r, src = n_edges_src) |>
    filter (seq <= 100) |>
    mutate (n_clusters = n_clusters / 5) |>
    pivot_longer (c (total, R, src, n_clusters)) |>
    mutate (name = recode_values (name,
        "total" ~ "Total",
        "R" ~ "R",
        "src" ~ "src",
        "n_clusters" ~ "Clusters"
    )) |>
    mutate (name = factor (name, levels = c ("Total", "R", "src", "Clusters"))) |>
    ggplot (aes (x = seq, y = value, colour = name)) +
    geom_line (lwd = 1.5) +
    xlab ("Release sequence") +
    ylab ("") +
    guides (color = guide_legend (ncol = 2)) +
    theme (
        text = element_text (size = 20),
        legend.title = element_blank (),
        legend.position = c (0.25, 0.90),
        legend.background = element_rect(fill = 'transparent', colour = NA),
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p14b

p14 <- p14a + p14b +
    plot_annotation (theme = theme (plot.background = element_rect (fill = "transparent", color = NA)))
ggsave (fig14_png, p14, bg = "transparent", width = 12, height = 7)
```




