```{r fig3-load}
library (pkgstatsAnalyses)
library (dplyr, quietly = TRUE, warn.conflicts = FALSE)
library (tidyr)
library (ggplot2)
library (patchwork)
```

```{r fig3-n-files-data-load}
here <- file.path (here::here (), "2026", "useR2026")
v_data_dir <- file.path (here, "data")
logmean <- function (x, ...) {
    10 ^ mean (log10 (x [which (x > 0)]), na.rm = TRUE)
}

datafile <- file.path (here, "data-raw", "pkgstats-results.Rds")
f_docs <- file.path (v_data_dir, "fig12b-documentation.Rds")

fig12b_png <- file.path (here, "img", "fig12b.png")
fig12c_png <- file.path (here, "img", "fig12c.png")
```

... Calculation code retained only in `pkgstats-analyses` repo.

```{r}
x <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE)
# CRAN snapshot values:
do1 <- function (x, year = 2018) {
    message (year)
    x |>
        filter (year <= !!year) |>
        group_by (package) |>
        slice_max (date) |>
        ungroup () |>
        summarise (
            files_vignettes = logmean (files_vignettes, na.rm = TRUE),
            loc_vignettes = logmean (loc_vignettes, na.rm = TRUE),
            doclines_per_fn_exp_mn = logmean (doclines_per_fn_exp_mn, na.rm = TRUE),
            doclines_per_fn_exp_md = logmean (doclines_per_fn_exp_md, na.rm = TRUE),
            doclines_per_fn_not_exp_mn = logmean (doclines_per_fn_not_exp_mn, na.rm = TRUE),
            doclines_per_fn_not_exp_md = logmean (doclines_per_fn_not_exp_md, na.rm = TRUE),
            docchars_per_par_exp_mn = logmean (docchars_per_par_exp_mn, na.rm = TRUE),
            docchars_per_par_exp_md = logmean (docchars_per_par_exp_md, na.rm = TRUE)
        ) |>
        mutate (year = year, .before = files_vignettes)
}
years <- sort (unique (x$year))
x_snapshot <- lapply (years, function (y) do1 (x, y))
x_snapshot <- do.call (rbind, x_snapshot)

x_annual <- x |>
    filter (!is.na (year)) |>
    group_by (year) |>
    summarise (
       files_vignettes = logmean (files_vignettes, na.rm = TRUE),
       loc_vignettes = logmean (loc_vignettes, na.rm = TRUE),
       doclines_per_fn_exp_mn = logmean (doclines_per_fn_exp_mn, na.rm = TRUE),
       doclines_per_fn_exp_md = logmean (doclines_per_fn_exp_md, na.rm = TRUE),
       doclines_per_fn_not_exp_mn = logmean (doclines_per_fn_not_exp_mn, na.rm = TRUE),
       doclines_per_fn_not_exp_md = logmean (doclines_per_fn_not_exp_md, na.rm = TRUE),
       docchars_per_par_exp_mn = logmean (docchars_per_par_exp_mn, na.rm = TRUE),
       docchars_per_par_exp_md = logmean (docchars_per_par_exp_md, na.rm = TRUE)
    ) |>
    mutate (year = year, .before = files_vignettes)

x_seq <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE) |>
    group_by (package) |>
    mutate (seq = seq_along (package)) |>
    ungroup () |>
    group_by (seq) |>
    summarise (
       files_vignettes = logmean (files_vignettes, na.rm = TRUE),
       loc_vignettes = logmean (loc_vignettes, na.rm = TRUE),
       doclines_per_fn_exp_mn = logmean (doclines_per_fn_exp_mn, na.rm = TRUE),
       doclines_per_fn_exp_md = logmean (doclines_per_fn_exp_md, na.rm = TRUE),
       doclines_per_fn_not_exp_mn = logmean (doclines_per_fn_not_exp_mn, na.rm = TRUE),
       doclines_per_fn_not_exp_md = logmean (doclines_per_fn_not_exp_md, na.rm = TRUE),
       docchars_per_par_exp_mn = logmean (docchars_per_par_exp_mn, na.rm = TRUE),
       docchars_per_par_exp_md = logmean (docchars_per_par_exp_md, na.rm = TRUE)
    )
saveRDS (list (snapshot = x_snapshot, annual = x_annual, sequential = x_seq), f_docs)
```

```{r}
dat <- readRDS (f_docs)

files_a <- dat$annual |>
    select (year, files_vignettes, loc_vignettes) |>
    mutate (what = "annual", lty = 1)
files_s <- dat$snapshot |>
    select (year, files_vignettes, loc_vignettes) |>
    mutate (what = "snapshot", lty = 2)
files <- rbind (files_a, files_s) |>
    filter (!is.na (files_vignettes) & !is.na (loc_vignettes)) |>
    rename (
        "Files" = files_vignettes,
        "Length (total lines)" = loc_vignettes
    ) |>
    mutate (lty = as.integer (lty)) |>
    filter (year >= 2014)

cols <- c ("Files" = "#F8766D", "Length (total lines)" = "#00BFC4")

range_files <- range (files$Files)
range_loc <- range (files$`Length (total lines)`)

files <- files |>
    mutate (loc_rescaled = scales::rescale (`Length (total lines)`, to = range_files, from = range_loc))

ggplot (files, aes (x = year)) +
    geom_line (aes (y = Files, col = "Files", lty = what), lwd = 1.5) +
    geom_line (aes (y = loc_rescaled, col = "Length (total lines)", lty = what), lwd = 1.5) +
    scale_color_manual (name = "", values = cols) +
    guides (linetype = "none") +
    scale_y_continuous (
        name = "Num. files",
        sec.axis = sec_axis (
            ~scales::rescale (., to = range_loc, from = range_files),
            name = "Length (total lines)")) +
    xlab ("Year") +
    theme (
        text = element_text (size = 20),
        legend.title = element_blank (),
        legend.position = c (0.3, 0.90),
        legend.background = element_rect(fill = 'transparent', colour = NA),
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p12b_one

files <- dat$sequential |>
    filter (!is.na (files_vignettes) & !is.na (loc_vignettes)) |>
    rename (
        "Files" = files_vignettes,
        "Length (total lines)" = loc_vignettes
    ) |>
    filter (seq <= 100)

range_files <- range (files$Files)
range_loc <- range (files$`Length (total lines)`)

files <- files |>
    mutate (loc_rescaled = scales::rescale (`Length (total lines)`, to = range_files, from = range_loc))

ggplot (files, aes (x = seq)) +
    geom_line (aes (y = Files, col = "Files"), lwd = 1.5) +
    geom_line (aes (y = loc_rescaled, col = "Length (total lines)"), lwd = 1.5) +
    scale_color_manual (name = "", values = cols) +
    guides (linetype = "none") +
    scale_y_continuous (
        name = "Num. files",
        sec.axis = sec_axis (
            ~scales::rescale (., to = range_loc, from = range_files),
            name = "Length (total lines)")) +
    xlab ("Release sequence") +
    theme (
        text = element_text (size = 20),
        legend.position = "none",
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p12b_two

p12b <- p12b_one + p12b_two +
    plot_annotation (theme = theme (plot.background = element_rect (fill = "transparent", color = NA)))
ggsave (fig12b_png, p12b, bg = "transparent", width = 12, height = 7)
```


```{r}
dat <- readRDS (f_docs)

files_a <- dat$annual |>
    select (year, doclines_per_fn_exp_md, docchars_per_par_exp_md) |>
    rename (
        doclines = doclines_per_fn_exp_md,
        docchars = docchars_per_par_exp_md
    ) |>
    mutate (what = "annual", lty = 1)
files_s <- dat$snapshot |>
    select (year, doclines_per_fn_exp_md, docchars_per_par_exp_md) |>
    rename (
        doclines = doclines_per_fn_exp_md,
        docchars = docchars_per_par_exp_md
    ) |>
    mutate (what = "snapshot", lty = 2)
files <- rbind (files_a, files_s) |>
    filter (!is.na (doclines) & !is.na (docchars)) |>
    rename (
        "Lines / fn" = doclines,
        "Chars / par" = docchars
    ) |>
    mutate (lty = as.integer (lty))

cols <- c ("Lines / fn" = "#F8766D", "Chars / par" = "#00BFC4")

range_lines <- range (files$`Lines / fn`)
range_chars <- range (files$`Chars / par`)

files <- files |>
    mutate (chars_rescaled = scales::rescale (`Chars / par`, to = range_lines, from = range_chars)) |>
    filter (year >= 2000)

ggplot (files, aes (x = year)) +
    geom_line (aes (y = `Lines / fn`, col = "Lines / fn", lty = what), lwd = 1.5) +
    geom_line (aes (y = chars_rescaled, col = "Chars / par", lty = what), lwd = 1.5) +
    scale_color_manual (name = "", values = cols) +
    guides (linetype = "none") +
    scale_y_continuous (
        name = "Lines / fn",
        sec.axis = sec_axis (
            ~scales::rescale (., to = range_chars, from = range_lines),
            name = "Chars / par")) +
    xlab ("Year") +
    theme (
        text = element_text (size = 20),
        legend.title = element_blank (),
        legend.position = c (0.3, 0.90),
        legend.background = element_rect(fill = 'transparent', colour = NA),
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p12c_one

files <- dat$sequential |>
    select (seq, doclines_per_fn_exp_md, docchars_per_par_exp_md) |>
    filter (!is.na (doclines_per_fn_exp_md) & !is.na (docchars_per_par_exp_md)) |>
    rename (
        "Lines / fn" = doclines_per_fn_exp_md,
        "Chars / par" = docchars_per_par_exp_md
    ) |>
    filter (seq <= 100)

range_lines <- range (files$`Lines / fn`)
range_chars <- range (files$`Chars / par`)

files <- files |>
    mutate (chars_rescaled = scales::rescale (`Chars / par`, to = range_lines, from = range_chars))

ggplot (files, aes (x = seq)) +
    geom_line (aes (y = `Lines / fn`, col = "Lines / fn"), lwd = 1.5) +
    geom_line (aes (y = chars_rescaled, col = "Chars / par"), lwd = 1.5) +
    scale_color_manual (name = "", values = cols) +
    guides (linetype = "none") +
    scale_y_continuous (
        name = "Lines / fn",
        sec.axis = sec_axis (
            ~scales::rescale (., to = range_chars, from = range_lines),
            name = "Chars / par")) +
    xlab ("Release sequence") +
    theme (
        text = element_text (size = 20),
        legend.title = element_blank (),
        legend.position = c (0.3, 0.90),
        legend.background = element_rect(fill = 'transparent', colour = NA),
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p12c_two

p12c <- p12c_one + p12c_two +
    plot_annotation (theme = theme (plot.background = element_rect (fill = "transparent", color = NA)))
ggsave (fig12c_png, p12c, bg = "transparent", width = 12, height = 7)
```


