```{r fig3-load}
library (pkgstatsAnalyses)
library (dplyr, quietly = TRUE, warn.conflicts = FALSE)
library (tidyr)
library (ggplot2)
library (patchwork)
```

```{r fig3-n-files-data-load}
here <- file.path (here::here (), "2026", "useR2026")
v_data_dir <- file.path (here, "data")
logmean <- function (x, ...) {
    10 ^ mean (log10 (x [which (x > 0)]), na.rm = TRUE)
}

datafile <- file.path (here, "data-raw", "pkgstats-results.Rds")
fig20_png <- file.path (here, "img", "fig20.png")
f_fig20 <- file.path (here, "data", "fig20-release-intervals.Rds")
```

```{r}
x <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE) |>
    select (package, date, year)

rel_intervals <- x |>
    filter (!is.na (date)) |>
    group_by (package) |>
    arrange (date) |>
    mutate (delta = as.numeric (date - lag (date))) |>
    filter (!is.na (delta)) |>
    mutate (seq = seq_along (date)) |>
    ungroup () |>
    group_by (seq) |>
    summarise (delta = mean (delta)) |>
    ungroup ()

rel_int23 <- x |>
    filter (!is.na (date)) |>
    group_by (package) |>
    arrange (date) |>
    mutate (delta = as.numeric (date - lag (date))) |>
    filter (!is.na (delta)) |>
    mutate (seq = seq_along (date)) |>
    ungroup () |>
    filter (seq %in% 1:4) |>
    group_by (year, seq) |>
    summarise (delta = mean (delta), .groups = "drop")

saveRDS (list (intervals = rel_intervals, int23 = rel_int23), f_fig20)
```

```{r}
cols <- c ("#F8766D", "#00BA38", "#619CFF")
readRDS (f_fig20)$intervals |>
    ggplot (aes (x = seq, y = delta)) +
    geom_line (lwd = 1.5, col = cols [2]) +
    xlab ("Release sequence") +
    ylab ("Interval (days)") +
    theme (
        text = element_text (size = 20),
        legend.title = element_blank (),
        legend.position = c (0.3, 0.90),
        legend.background = element_rect(fill = 'transparent', colour = NA),
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p20a

readRDS (f_fig20)$int23 |>
    mutate (
        lwd = 2 - (seq - 1) / 3,
        seq = factor (seq, levels = c ("1", "2", "3", "4"))
    ) |>
    ggplot (aes (x = year, y = delta, linetype = seq, linewidth = lwd)) +
    geom_line (col = cols [2]) +
    scale_linetype_manual (
        values = c ("solid", "dashed", "dotted", "dotdash"),
        labels = c ("2nd release", "3rd release", "4th release", "5th release"),
        guide = guide_legend (
            override.aes = list (linewidth = c (2, 2 - 1 / 3, 2 - 2 / 3, 1))
        )
    ) +
    scale_linewidth_identity () +
    xlab ("Year") +
    ylab ("Interval (days)") +
    theme (
        text = element_text (size = 20),
        legend.title = element_blank (),
        legend.position = c (0.25, 0.85),
        legend.background = element_rect(fill = 'transparent', colour = NA),
        panel.background = element_rect(fill = 'transparent'),
        plot.background = element_rect(fill = 'transparent', color = NA),
        panel.grid.major = element_line(colour = "gray70", linetype = 2),
        legend.box.background = element_rect(fill = 'transparent', colour = NA)
    ) -> p20b
p20 <- p20a + p20b +
    plot_annotation (theme = theme (plot.background = element_rect (fill = "transparent", color = NA)))
ggsave (fig20_png, p20, bg = "transparent", width = 12, height = 7)
```


